// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lopez_Tomas_Examen_Progreso_1.Migrations
{
    [DbContext(typeof(LopezTomas_Context))]
    partial class LopezTomas_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lopez_Tomas_Examen_Progreso_1.Models.Celular", b =>
                {
                    b.Property<int>("IDcelular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDcelular"));

                    b.Property<int>("año")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.HasKey("IDcelular");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("Lopez_Tomas_Examen_Progreso_1.Models.Lopez", b =>
                {
                    b.Property<int>("IDlopez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDlopez"));

                    b.Property<int>("Ncelular")
                        .HasColumnType("int");

                    b.Property<bool>("afiliado")
                        .HasColumnType("bit");

                    b.Property<int?>("celularIDcelular")
                        .HasColumnType("int");

                    b.Property<float>("decFav")
                        .HasColumnType("real");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDlopez");

                    b.HasIndex("celularIDcelular");

                    b.ToTable("Lopez");
                });

            modelBuilder.Entity("Lopez_Tomas_Examen_Progreso_1.Models.Lopez", b =>
                {
                    b.HasOne("Lopez_Tomas_Examen_Progreso_1.Models.Celular", "celular")
                        .WithMany()
                        .HasForeignKey("celularIDcelular");

                    b.Navigation("celular");
                });
#pragma warning restore 612, 618
        }
    }
}
